swagger: '2.0'
info:
  title: Atlassin MCP Server
  description: MCP Server using Streamable HTTP transport for Copilot Studio
  version: 0.1.0
host: atlassinmcp.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /{connectionId}/mcp:
    post:
      summary: Atlassin MCP Server Endpoint
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      consumes:
        - application/json
      produces:
        - application/json
        - text/event-stream
      responses:
        '200':
          description: Success
  /healthz:
    get:
      summary: Health probe
      operationId: Healthz
      produces:
        - text/plain
      responses:
        '200':
          description: OK
