swagger: '2.0'
info:
  title: Atlassin MCP Server
  description: MCP Server using Streamable HTTP transport for Copilot Studio
  version: 0.1.0
host: atlassinmcp.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Atlassin MCP Server Endpoint
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      consumes:
        - application/json
      produces:
        - application/json
        - text/event-stream
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              jsonrpc:
                type: string
                enum: ['2.0']
              method:
                type: string
                description: JSON-RPC method (initialize, tools/list, tools/call)
              id:
                type: string
                description: JSON-RPC id (string or integer). Represented as string here for Swagger 2.0 compatibility.
              params:
                type: object
            required: [jsonrpc, method]
      responses:
        '200':
          description: Success
    get:
      summary: Server-Sent Events stream (optional)
      produces:
        - text/event-stream
      responses:
        '200':
          description: SSE stream
  /healthz:
    get:
      summary: Health probe
      operationId: Healthz
      produces:
        - text/plain
      responses:
        '200':
          description: OK
