swagger: '2.0'
info:
  title: Atlassian MCP Server
  description: MCP Server using Streamable HTTP transport for Copilot Studio - supports up to 100 Confluence search results with dynamic token management to prevent overflow (JSON-first; optional SSE)
  version: 0.1.1
host: atlassian-mcp.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Atlassian MCP Server Endpoint
      description: >
        Accepts MCP Streamable HTTP JSON-RPC messages (initialize, tools/list, tools/call). 
        Returns JSON by default and supports Server-Sent Events when requested via 
        `Accept: text/event-stream`. Includes `Mcp-Session-Id` header on initialize.
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      consumes:
        - application/json
      produces:
        - application/json
        - text/event-stream
      responses:
        '200':
          description: Success
  /healthz:
    get:
      summary: Health probe
      description: >
        Liveness endpoint that returns 'ok' when the service is running; useful 
        for Azure App Service health checks.
      operationId: Healthz
      produces:
        - text/plain
      responses:
        '200':
          description: OK
