name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: npm prune --production
      - name: Create release package
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p release
          cp -r dist release/dist
          cp package.json release/
          cp package-lock.json release/
          cp -r node_modules release/node_modules
          cp openapi-mcp.yaml release/
          if [ -f Procfile ]; then cp Procfile release/; fi
      - uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/download-artifact@v4
        with:
          name: node-app
          path: node-app
      - id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ./node-app
          startup-command: 'node dist/server.js'
